version: "3.7"

services:
  beacon:
    container_name: beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${PRYSM_DOCKER_TAG:-stable}
    restart: always
    hostname: beacon-chain
    command: --config-file=/config/beacon.yaml
    ports:
      - 127.0.0.1:4000:4000
      - 13000:13000/tcp
      - 12000:12000/udp
    volumes:
      - ./scripts/beacon.yaml:/config/beacon.yaml:ro
      - beacon_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  beacon_data:
